### PR TITLE
Add empty screen

### LINKED ISSUE #684: Tela de nenhum registro encontrado
## Feature Description

Definir um layout mais amigável para informar que não existem registros no item consultado. Similar a essa aqui

Dashboard

É mais para deixar o item centralizado na tela, com uma imagem em cima e o texto personalizado abaixo, como por exemplo, quando não existirem tecnologias cadastradas o texto continua sendo: Você não possui tecnologias para exibir até o momento!

---------------

## Acceptance criteria

* 

## Implementation Brief

*

### PR DESCRIPTION
**Pull request by luizeboli**
## Summary

Resolves #684

image

## Relevant technical choices

* I've created a component called `EmptyScreen` which can be reused between pages, later we can implement custom images too.

## QA Steps

1. Login
2. Access any user account page that has no registries
3. The new empty screen layout must be shown

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code passes the linting.
- [x] My code has proper inline documentation.
- [x] I have manually tested this PR.

### CODE REVIEW

**Review by mateus4k — APPROVED** [review]
LGTM
🚀

**Review by mateus4k — APPROVED** [review]

**Review by calaca — APPROVED** [review]
Awesome work, Felicio! :clap: 

I've noticed, though, that we don't have this `EmptyScreen` component being used on reviewer pages like this one:
image

Is this feature for "default" users only?

**Comment by luizeboli** [comment]
No @calaca, I really forgot to add into these screens. Will do it

**Review by mateus4k — CHANGES_REQUESTED** [review]
👆

**Review by mateus4k — APPROVED** [review]
Merry Christmas!

**Review by calaca — APPROVED** [review]
Approved!

Merry Christmas! :gift: :rofl:

**Review by lcnogueira — APPROVED** [review]

**Review by mateus4k — APPROVED** [review]

**Review by calaca — APPROVED** [review]

**Pull request merged**
